//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loyalty
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductLine()
        {
            this.Quantity = 0;
            this.Status = true;
            this.Progress = "Processing";
        }
    
        public long Id { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TrackingNumber { get; set; }
        public long ProductId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Progress { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
